if(NOT BUILD_GAME)
    return()
endif()

if(NOT ENGINE_VERSION_REQUIRED)
	message(FATAL_ERROR "ENGINE_VERSION_REQUIRED must be specified.")
endif()

string(REPLACE "." ";" ENGINE_VERSION_REQUIRED_LIST ${ENGINE_VERSION_REQUIRED})
list(GET ENGINE_VERSION_REQUIRED_LIST 0 ENGINE_VERSION_REQUIRED_MAJOR)
list(GET ENGINE_VERSION_REQUIRED_LIST 1 ENGINE_VERSION_REQUIRED_MINOR)

if(NOT (ENGINE_VERSION_REQUIRED_MAJOR EQUAL PROJECT_VERSION_MAJOR AND ENGINE_VERSION_REQUIRED_MINOR EQUAL PROJECT_VERSION_MINOR))
	message(WARNING "The required engine version for the project is ${ENGINE_VERSION_REQUIRED}, but the current version is ${PROJECT_VERSION}. There may be a problem.")
endif()
